;;; compleseus-spacemacs-help-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from compleseus-spacemacs-help.el

(autoload 'compleseus-spacemacs-help-docs "compleseus-spacemacs-help" "\


(fn ARG)" t)
(autoload 'compleseus-spacemacs-help-layers "compleseus-spacemacs-help" nil t)
(autoload 'compleseus-spacemacs-help "compleseus-spacemacs-help" nil t)
(defalias 'compleseus-spacemacs-help-packages 'compleseus-spacemacs-help)
(autoload 'compleseus-spacemacs-help-toggles "compleseus-spacemacs-help" nil t)
(autoload 'compleseus-spacemacs-help-dotspacemacs "compleseus-spacemacs-help" nil t)
(autoload 'compleseus-spacemacs-help-faq "compleseus-spacemacs-help" "\
Show FAQ and launch swiper session." t)
(register-definition-prefixes "compleseus-spacemacs-help" '("compleseus-spacemacs-"))

;;; End of scraped data

(provide 'compleseus-spacemacs-help-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; compleseus-spacemacs-help-autoloads.el ends here
