;;; evil-ghostel-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from evil-ghostel.el

(autoload 'evil-ghostel-mode "evil-ghostel" "\
Minor mode for Evil integration in ghostel terminal buffers.

Binds Evil operators to terminal-aware variants and keeps point aligned
with the terminal cursor across Evil state transitions.

Enabling installs global advice while any buffer has the mode enabled.

This is a minor mode.  If called interactively, toggle the `Evil-Ghostel
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `evil-ghostel-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "evil-ghostel" '("evil-ghostel-"))

;;; End of scraped data

(provide 'evil-ghostel-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; evil-ghostel-autoloads.el ends here
