;;; orgox-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from orgox.el

(autoload 'orgox-export-current-buffer "orgox" "\
Export the current buffer, which should hold a note, to an ox-hugo file." t)
(autoload 'orgox-publish-current-buffer "orgox" "\
Publish the current buffer, which should hold a note, to an ox-hugo file." t)
(register-definition-prefixes "orgox" '("orgox-"))

;;; End of scraped data

(provide 'orgox-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; orgox-autoloads.el ends here
