;;; evil-iedit-state-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from evil-iedit-state.el

(eval-after-load 'expand-region '(progn (defun evil-iedit-state/iedit-mode-from-expand-region (&optional arg) "Start `iedit-mode'." (interactive "P") (evil-iedit-state/iedit-mode arg) (setq overriding-terminal-local-map nil)) (define-advice er/prepare-for-more-expansions-internal (:around (orig-fun &rest args) evil-iedit-state) (let* ((result (apply orig-fun args)) (default-msg (car result)) (default-bindings (cdr result))) (cons (concat default-msg ", e to edit") (add-to-list 'default-bindings '("e" evil-iedit-state/iedit-mode-from-expand-region)))))))
(register-definition-prefixes "evil-iedit-state" '("evil-iedit-state" "iedit-done"))

;;; End of scraped data

(provide 'evil-iedit-state-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; evil-iedit-state-autoloads.el ends here
