;;; uv-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from uv.el

 (autoload 'uv "uv" nil t)
(autoload 'uv-add-dep "uv" "\
Add PACKAGE-STRING (space-separated) as new dependencies.
Uses ``uv add''.

(fn PACKAGE-STRING)" t)
(autoload 'uv-add-dev-dep "uv" "\
Add PACKAGE-STRING (space-separated) as new development dependencies.
Uses ``uv add -D''.

(fn PACKAGE-STRING)" t)
(autoload 'uv-add-opt-dep "uv" "\
Add PACKAGE as a new optional dependency to the project.

PACKAGE can be a list of packages, separated by spaces.

(fn PACKAGE)" t)
(autoload 'uv-remove "uv" "\
Remove PACKAGE from the project dependencies.
TYPE is the type of dependency (dep, dev or opt).

(fn PACKAGE TYPE)" t)
(autoload 'uv-install-install "uv" "\
Install the project dependencies." t)
(autoload 'uv-lock "uv" "\
Locks the project dependencies." t)
(autoload 'uv-build "uv" "\
Build a package, as a tarball and a wheel by default." t)
(autoload 'uv-publish "uv" "\
Publish the package to a remote repository.

REPO is the repository and USERNAME and PASSWORD the
credential to use.

(fn REPO USERNAME PASSWORD)" t)
(autoload 'uv-new "uv" "\
Create a new Python project at PATH.

(fn PATH)" t)
(autoload 'uv-init "uv" "\
Initialize a new Uv project." t)
(autoload 'uv-edit-pyproject-toml "uv" "\
Open the current project `pyproject.toml' file for edition." t)
(autoload 'uv-run "uv" "\
Run COMMAND in the appropriate environment.

(fn COMMAND)" t)
(autoload 'uv-find-project-root "uv" "\
Return the uv project root if any.")
(register-definition-prefixes "uv" '("uv-"))

;;; End of scraped data

(provide 'uv-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; uv-autoloads.el ends here
