;;; js-doc-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from js-doc.el

(autoload 'js-doc-insert-file-doc "js-doc" "\
Insert specified-style comment top of the file" t)
(autoload 'js-doc-insert-function-doc "js-doc" "\
Insert JsDoc style comment of the function
The comment style can be custimized via `customize-group js-doc'" t)
(autoload 'js-doc-insert-function-doc-snippet "js-doc" "\
Insert JsDoc style comment of the function with yasnippet." t)
(autoload 'js-doc-insert-tag "js-doc" "\
Insert a JsDoc tag interactively." t)
(autoload 'js-doc-describe-tag "js-doc" "\
Describe the JsDoc tag" t)
(register-definition-prefixes "js-doc" '("js-doc-"))

;;; End of scraped data

(provide 'js-doc-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; js-doc-autoloads.el ends here
