;;; uv-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from uv.el

 (autoload 'uv "uv" nil t)
(autoload 'uv-add-dep "uv" "\
Add PACKAGE-STRING (space-separated) as new dependencies.
Uses ``uv add''.

(fn PACKAGE-STRING)" t)
(autoload 'uv-add-dev-dep "uv" "\
Add PACKAGE-STRING (space-separated) as new development dependencies.
Uses ``uv add --dev''.

(fn PACKAGE-STRING)" t)
(autoload 'uv-add-opt-dep "uv" "\
Add PACKAGE-STRING (space-separated) to the optional dependency EXTRA.
Uses ``uv add --optional''.

(fn PACKAGE-STRING EXTRA)" t)
(autoload 'uv-remove "uv" "\
Remove a dependency from the project.
ARGS are the ``uv remove'' arguments naming the package and its group.

(fn ARGS)" t)
(autoload 'uv-lock "uv" "\
Locks the project dependencies." t)
(autoload 'uv-build "uv" "\
Build a package, as a tarball and a wheel by default." t)
(autoload 'uv-init "uv" "\
Initialize a new Uv project." t)
(autoload 'uv-edit-pyproject-toml "uv" "\
Open the current project `pyproject.toml' file for edition." t)
(autoload 'uv-run "uv" "\
Run COMMAND in the project environment.

(fn COMMAND)" t)
(autoload 'uv-show-output "uv" "\
Display the output of the last uv command." t)
(autoload 'uv-find-project-root "uv" "\
Return the uv project root if any.")
(register-definition-prefixes "uv" '("uv-"))

;;; End of scraped data

(provide 'uv-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; uv-autoloads.el ends here
